---
#-------------------------------
# General Site Settings

title: SHLBY
logo: "assets/images/logo/87269494.png"
author: SHLBY
description: dev & analytics
email:
phone:
address:
copyright: Copyright &copy; Twenty Twenty-Two Designed by SHLBY, based on [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  # - { name: Blog, link: "/blog" }
  # - { name: Portfolio, link: "/portfolio" }
  # - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: <img src="/assets/images/logo/SHLBY.png"> #<h1 class="text-white font-tertiary">SHLBY</h1>

social:
  - { icon: "ti-facebook", link: "#" }
  - { icon: "ti-instagram", link: "#" }
  - { icon: "ti-dribbble", link: "#" }
  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: An innovative data analytics and development team, SHLBY prides itself on providing invaluable insight and services with superior professionalism. Established in twenty twenty-two, we look to disrupt the technology industry with our expertise in our world of data. With experience in analytics, big data, software, and pipeline development collaborate with our team for solutions and best-in-class development for your coding and analytics needs.
blurb-btn-link: "/about"
blurb-btn-name: learn more

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "Collecting, organizing, and analyzing various forms of data and information for the purpose of solving problems."

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Transformation of user requirements into suitable forms for future implementation of models and software."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Continuous and reliable production of deliverables in a timely manner with unparalleled professionalism."

# The Team Section
team:
  - title: "Shel"
    image: "assets/images/team/IMG_0577.jpg"
    designation: "Data Scientist, CEO"

  - title: "Tay"
    image: "assets/images/team/IMG_0578.jpg"
    designation: "Software Engineer"

  - title: "Terra"
    image: "assets/images/team/IMG_0575.jpg"
    designation: "Data Analyst"

#-------------------------------
# Skills Section

# skills-title: Skills
# skills:
#   - { name: Analytics, color: "#fdb157", value: "90%" }
#   - { name: Machine Learning, color: "#9473e6", value: "70%" }
#   - { name: Software Development, color: "#bdecf6", value: "50%" }

#-------------------------------
# Exprerience Section

# experience-title: Experience
# experience:
#   - {
#       name: Junior UX Designer,
#       icon: "icon-1.png",
#       date: "Jan 2007 - Feb 2009",
#       organization: "WEBEX",
#     }
#   - {
#       name: UX & UI Designer,
#       icon: "icon-2.png",
#       date: "Mar 2009 - Aug 2014",
#       organization: "AUGMEDIX",
#     }
#   - {
#       name: Senior UI Designer,
#       icon: "icon-3.png",
#       date: "Sep 2014 - Present",
#       organization: "THEMEFISHER",
#     }

#-------------------------------
# Education Section

# education-title: Education
# education:
#   - {
#       name: Marters in UX Design,
#       date: "2006",
#       organization: "Masassusets Institute of Technology",
#     }
#   - {
#       name: Honours in Fine Arts,
#       date: "2004",
#       organization: "Harvard University",
#     }
#   - {
#       name: Higher Secondary Certificat,
#       date: "2000",
#       organization: "Cardiff School",
#     }
#   - {
#       name: Secondary School Certificate,
#       date: "1998",
#       organization: "Cardiff School",
#     }

#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: Data Analytics,
      icon: ti-bar-chart,
      description: "Analysis of raw data to create insight and form conclusions about the original data information.",
      active: true, # Add true to select section
    }
  - {
      name: Machine Learning,
      icon: ti-vector,
      description: "Data acquisition and data processing for implementation of algorithms for key decisions using data.",
      active: true, # Add true to select section
    }
  - {
      name: Software Development,
      icon: ti-panel,
      description: "Activities dedicated to the process of creating, designing, deploying and supporting software.",
      active: false, # Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# # Portfolio Home Section
# portfolio-home-items:
#   - image: "assets/images/portfolio/item-1.png"
#     url: "#"
#
#   - image: "assets/images/portfolio/item-2.png"
#     url: "#"
#
#   - image: "assets/images/portfolio/item-3.png"
#     url: "#"
#
#   - image: "assets/images/portfolio/item-4.png"
#     url: "#"
#
#   - image: "assets/images/portfolio/item-5.png"
#     url: "#"
#
# # Portfolio Page
# portfolio-label:
#   - { title: "UI/UX Design", type: "design" }
#   - { title: "BRANDING", type: "branding" }
#   - { title: "ILLUSTRATION", type: "illustration" }
#
# portfolio-items:
#   - image: "assets/images/portfolio/item-1.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#       - type: "illustration"
#
#   - image: "assets/images/portfolio/item-2.png"
#     url: "#"
#     portfolio-type:
#       - type: "branding"
#
#   - image: "assets/images/portfolio/item-3.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"
#
#   - image: "assets/images/portfolio/item-6.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#       - type: "branding"
#
#   - image: "assets/images/portfolio/item-8.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"
#
#   - image: "assets/images/portfolio/item-5.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#
#   - image: "assets/images/portfolio/item-1.png"
#     url: "#"
#     portfolio-type:
#       - type: "branding"
#
#   - image: "assets/images/portfolio/item-3.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#       - type: "illustration"
#       - type: "branding"
#
#   - image: "assets/images/portfolio/item-7.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"

#-------------------------------
# Testimonials Section

# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
#
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
#
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------
# Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
#
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
#
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
#
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
#
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"
#
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
#
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
#
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
#
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
#
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: ____ @ email.com
